steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA)
        for file in $FILES; do
          CONTENT=$(cat "$file")
          curl -X POST https://code-review-service-cwmu2ywqna-uc.a.run.app/review \
            -H "Content-Type: application/json" \
            -d "{\"filename\":\"$file\",\"content\":\"$CONTENT\"}"
        done
